name: Check Renovate Configuration

on:
  pull_request:
    branches:
      - main
    # Only watch root level Renovate configuration changes
    paths:
      - 'renovate.json*'

jobs:
  analysis-results:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GIT Repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Setup node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version-file: '.nvmrc'

    - name: Run renovate-config-validator
      run: npx --yes --package renovate@41.173.1 -- renovate-config-validator
