name: Check Renovate Configuration

on:
  pull_request:
    branches:
      - main
    # Only watch root level Renovate configuration changes
    paths:
      - 'renovate.json*'

jobs:
  analysis-results:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GIT Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Setup node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version-file: '.nvmrc'

    - name: Run renovate-config-validator
      run: npx --yes --package renovate@43.224.0 -- renovate-config-validator
