name: Check Renovate Configuration

on:
  pull_request:
    branches:
      - main
    # Only watch root level Renovate configuration changes
    paths:
      - 'renovate.json*'

jobs:
  analysis-results:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GIT Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Setup node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: '.nvmrc'

    - name: Run renovate-config-validator
      run: npx --yes --package renovate@41.82.10 -- renovate-config-validator
