name: Commit Results

on:
  workflow_call:
    inputs:
      commit-author-name:
        description: "The display name of the commit author"
        required: false
        type: string
        default: '${{ github.event.repository.name }} Continuous Integration'
      commit-author-email:
        description: "The email address of the commit author"
        required: true
        type: string
      commit-message:
        description: "The commit message"
        required: false
        type: string
        default: "ci: Add automated results"
      commit-directory:
        description: "The directory to commit"
        required: true
        type: string
      uploaded-artifact-name:
        description: "The name of the uploaded artifact"
        required: true
        type: string
    secrets:
      repository-commit-token:
        description: "The token to use for committing to the repository"
        required: true

jobs:
  commit-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GIT Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.repository-commit-token }}

      - name: Download artifacts to commit
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: ${{ inputs.uploaded-artifact-name }}
          path: ${{ inputs.commit-directory }}

      - name: Display environment variable "github.event_name"
        run: echo "github.event_name=${{ github.event_name }}"

      - name: Prepare commit of changes in `${{ inputs.commit-directory }}`
        run: |
          git config --global user.name '${{ inputs.commit-author-name }}'
          git config --global user.email '${{ inputs.commit-author-email }}'
          git config --local http.postBuffer 524288000
          git fetch origin
          git status
          git add ${{ inputs.commit-directory }}
          git status

      - name: Commit and push changes in `${{ inputs.commit-directory }}`
        # Only run when a pull request gets merged or a commit is pushed to the main branch
        if: github.event_name == 'push'
        run: |
          git commit --message "${{ inputs.commit-message }}"
          git status
          git rebase --strategy-option=theirs origin/main --verbose
          git status
          git add ${{ inputs.commit-directory }}
          git status
          git push --verbose
