name: AxonFramework Code Graph Analysis (Java)

on:
  push:
    branches:
      - main
    # Ignore changes in documentation, general configuration and analysis-results for push events
    paths-ignore: 
      - 'analysis-results/**'
      - '**/*.md'
      - '**/*.txt'
      - '**/*.css'
      - '**/*.html'
      - '**/*.js'
      - '.gitignore'
      - '.gitattributes'
      - 'renovate.json'
      - '**.code-workspace'
      - '.github/workflows/typescript-code-analysis.yml'
      - '.github/workflows/*documentation.yml'
  pull_request:
    branches:
      - main
    # Ignore changes in documentation, general configuration and analysis-results for pull request events
    paths-ignore: 
      - 'analysis-results/**'
      - '**/*.md'
      - '**/*.txt'
      - '**/*.css'
      - '**/*.html'
      - '**/*.js'
      - '.gitignore'
      - '.gitattributes'
      - 'renovate.json'
      - '**.code-workspace'
      - '.github/workflows/typescript-code-analysis.yml'
      - '.github/workflows/*documentation.yml'

jobs:
  prepare-code-to-analyze:
    name: Prepare Code to Analyze
    runs-on: ubuntu-latest
    env: 
      PROJECT_NAME: AxonFramework
      # Version variable names matches renovate.json configuration entry
      AXON_FRAMEWORK_VERSION: 4.10.3
      # Java is in this example only used to download JARs for analysis using Maven
      JAVA_VERSION: 21
    outputs:
      project-name: ${{ env.PROJECT_NAME }}
      analysis-name: ${{ steps.set-analysis-name.outputs.analysis-name }}
      sources-upload-name: ${{ steps.set-sources-upload-name.outputs.sources-upload-name }}
      artifacts-upload-name: ${{ steps.set-artifacts-upload-name.outputs.artifacts-upload-name }}

    steps:
    - name: (Prepare Code to Analyze) Checkout AxonFramework repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        repository: AxonFramework/AxonFramework
        ref: axon-${{ env.AXON_FRAMEWORK_VERSION }}
        path: ./source

    - name: (Prepare Code to Analyze) Setup Java Development Kit for Maven JARs downloading (JDK) ${{ env.JAVA_VERSION}}
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
      with:
        distribution: "temurin"
        java-version: ${{ env.JAVA_VERSION}}

    - name: (Prepare Code to Analyze) Download AxonFramework JARs for analysis
      run: |
        mvn dependency:copy -Dartifact=org.axonframework:axon-configuration:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-disruptor:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-eventsourcing:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-messaging:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-modelling:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-test:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-server-connector:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-spring-boot-autoconfigure:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
        mvn dependency:copy -Dartifact=org.axonframework:axon-tracing-opentelemetry:${{ env.AXON_FRAMEWORK_VERSION }} -DoutputDirectory=./artifacts
 
    - name: (Prepare Code to Analyze) Set analysis-name
      id: set-analysis-name
      run: echo "analysis-name=${{ env.PROJECT_NAME }}-${{ env.AXON_FRAMEWORK_VERSION }}" >> "$GITHUB_OUTPUT"

    - name: (Prepare Code to Analyze) Generate ARTIFACT_UPLOAD_ID
      run: echo "ARTIFACT_UPLOAD_ID=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 10)" >> $GITHUB_ENV
 
    - name: (Prepare Code to Analyze) Set sources-upload-name
      id: set-sources-upload-name
      run: echo "sources-upload-name=${{ steps.set-analysis-name.outputs.analysis-name }}-analysis-sources_input-${{ env.ARTIFACT_UPLOAD_ID }}" >> "$GITHUB_OUTPUT"
 
    - name: (Prepare Code to Analyze) Assemble ARTIFACTS_UPLOAD_NAME
      id: set-artifacts-upload-name
      run: echo "artifacts-upload-name=${{ steps.set-analysis-name.outputs.analysis-name }}-analysis-artifacts-input-${{ env.ARTIFACT_UPLOAD_ID }}" >> "$GITHUB_OUTPUT"

    - name: (Prepare Code to Analyze) Upload sources to analyze
      if: success()
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
      with:
        name: ${{ steps.set-sources-upload-name.outputs.sources-upload-name }}
        path: ./source
        include-hidden-files: true
        if-no-files-found: error
        retention-days: 1

    - name: (Prepare Code to Analyze) Upload artifacts to analyze
      if: success()
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
      with:
        name: ${{ steps.set-artifacts-upload-name.outputs.artifacts-upload-name }}
        path: ./artifacts
        if-no-files-found: error
        retention-days: 1


  analyze-code-graph:
    name: Analyze Code Graph
    needs: [prepare-code-to-analyze]
    uses: JohT/code-graph-analysis-pipeline/.github/workflows/public-analyze-code-graph.yml@7f43cf96d676f715cf278b020ce1dbb3338f900b # v2
    with:
      analysis-name: ${{ needs.prepare-code-to-analyze.outputs.analysis-name }}
      artifacts-upload-name: ${{ needs.prepare-code-to-analyze.outputs.artifacts-upload-name }}
      sources-upload-name: ${{ needs.prepare-code-to-analyze.outputs.sources-upload-name }}
      ref: 7f43cf96d676f715cf278b020ce1dbb3338f900b


  commit-analysis-results:
    name: Commit Analysis Results
    needs: [prepare-code-to-analyze, analyze-code-graph]
    uses: ./.github/workflows/internal-commit-results.yml
    with:
      commit-author-name: "${{ github.event.repository.name }} Continuous Integration"
      commit-author-email: "7671054+JohT@users.noreply.github.com"
      commit-message: "Automated code structure analysis results (CI)"
      commit-directory: "analysis-results/${{ needs.prepare-code-to-analyze.outputs.project-name }}/${{ needs.prepare-code-to-analyze.outputs.analysis-name }}"
      uploaded-artifact-name: ${{ needs.analyze-code-graph.outputs.uploaded-analysis-results }}
    secrets:
      repository-commit-token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}